const Lang = {
  year: "Year",
  backToToday: "Nimadir",
  clear: "Clear",
  dayFormat: "24",
  month: "Month",
  now: "Hozir",
  today: "Today",
  previousYear: "Avvalgi yil",
  nextYear: "Keyingi yil",
  nextMonth: "Keyingi oy",
  previousMonth: "Avvalgi oy",
  previousCentury: "as",
  nextCentury: "as",
  nextDecade: "as1",
  previousDecade: "as1",
  ok: "OK",
  locale: "LOCAL",
  yearSelect: "Yila",
  dateFormat: "nimadir",
  dateSelect: "select",
  dateTimeFormat: "form",
  monthSelect: "oy select",
  yearFormat: "YYYY",
  decadeSelect: "decade select",
  placeholder: "Hello guys",
  timeSelect: "Time select",
};

export default Lang;
